### ISSUE TITLE
Merge Improvements in main.py for Enhanced User Experience

### ISSUE THREAD

**Issue by hackergandhi** [hackergandhi/LockBoxXtreme#17]
## Describe the bug

I have implemented significant improvements in `main.py` to enhance user experience and provide better security. This updated version includes a master password setup, a more engaging UI, and smoother interactions.

## Details of the Improvements:

**Master Password Setup:**

- Added a feature for users to create a master password during the initial setup.
- Validates the master password for a minimum of 8 characters, including upper and lower case letters, digits, and special characters.

**Enhanced User Interface:**

- Designed a more attractive interface using ASCII art for the welcome screen.
- The interface now has a terminal-like appearance with colors for better readability.

**Terminal-Like Experience:**

- The screen clears automatically when the program starts, displaying only the password manager interface.
- Provides a focused and distraction-free experience.

**Colorful and Emoji-Rich Experience:**

- Introduced colors and emojis to make the interface more engaging and user-friendly.
- Provides visual feedback for user actions like successful operations and errors.

**Better Navigation:**

- After each action (e.g., storing or retrieving a password), the menu is displayed automatically for smoother interaction.
- Users can easily navigate through different options without needing to restart the program.

**Impact:** These updates aim to improve user satisfaction by making the application easier to use and more secure. The new version ensures that user data is protected by requiring a master password, while the enhanced UI makes the tool more appealing.

**Action Required:**

- Review the updated `main.py` file and provide feedback.
- Merge the changes if everything looks good.
- Any further suggestions for improvements are welcome!

**Comment by i3hz** [comment]
sorry i was kinda busy for a while 
but yeah it looks good to me. Tho the ascii UI is kinda funny lmao . I could do a basic flask/pygame/tk UI if you want. Nothing too fancy but it will be a decent UI

**Comment by hackergandhi** [comment]
Yeah, go ahead and make the changes! Just make sure to do a thorough debugging before wrapping it up, so there aren’t any issues. And once you're done, let me know exactly what you changed and what you kept the same

**Comment by i3hz** [comment]
welp i did create a basic flask app lmk , if yall want any changes. i've had exams for a while and im going to visit my parents for a bit , so imma be gone for a bit
https://github.com/i3hz/LockBoxXtreme

check my fork of the repo , lmk if there are any issues

**Comment by hackergandhi** [comment]
@i3hz 

Yo, bruh! Your concept's lit, but you're missin' all the fire features, fam! Lockboxxtreme had password retrieval, extra sec, and all that jazz. Yours just got master password and storage, G. Step up and add the rest, or nah? If you do, I'll cop $50, INR style, no cap!

**Comment by hackergandhi** [comment]
where u from? if india so payment method is easy because i’m also indian

**Comment by i3hz** [comment]
yeah sure i'll try.
yes im from india .
happy belated diwali mate

**Comment by i3hz** [comment]
also probably a dumb question but these functions are not defined anywhere so why is the code working :store_password, retrieve_password, delete_service, backup_passwords, restore_passwords, generate_random_password

**Comment by hackergandhi** [comment]
hi @i3hz 

> also probably a dumb question but these functions are not defined anywhere so why is the code working store_password, retrieve_password, delete_service, backup_passwords, restore_passwords, generate_random_password

thanks for flagging those functions! I checked the code, and it looks like `store_password`, `retrieve_password`, `delete_service`, `backup_passwords`, `restore_passwords`, and `generate_random_password` are referenced but not actually defined in `main.py`. They might have been in a separate module or file initially, or @Hackerjatti32 missed adding them during an update but we’ll need them in the tool

**To keep things on track:**

- If you see these functions in any previous commits or modules, let me know where

If you’re up for it, feel free to add them as you work on the UI, or you can keep focusing on the interface if that's easier. Either way works—do what feels best, and let me know if you need any details on how those functions should work. Appreciate the help in making this tool better!

**Comment by i3hz** [comment]
I could try working on it 
In an older commit 
 I found that they are getting import from storage
from storage import add_password, retrieve_password, delete_service, load_passwords, save_passwords
i think this was when the script had multiple files .

>Appreciate the help in making this tool better!
The pleasure is all mine :)

**Comment by hackergandhi** [comment]
Hi @i3hz,

Thank you so much for looking into this and taking the time to help with the project. I truly appreciate the effort you're putting into improving the tool, especially with all the commitments you’ve had recently!

**A quick background:** this project was assigned to me as part of my college assignment, and due to other academic deadlines, I couldn’t respond earlier—apologies for the delay! Your contributions mean a lot, as I need to get this finalized soon to submit it.

About the issue with the undefined functions: thanks for pointing it out! It looks like these functions were originally part of a separate module (storage), which might have been overlooked during a reorganization. I’ll double-check the older commits to retrieve the storage module, but if you could help reintegrate or redefine these functions while refining the UI, that would be incredibly helpful. The functionalities they covered include:

- **`store_password`:** To securely store a new password.
- **`retrieve_password`:** To fetch stored passwords.
- **`delete_service`:** To remove a password entry.
- **`backup_passwords` & `restore_passwords`:** For backup and recovery.
- **`generate_random_password`:** For generating secure random passwords.

Let me know if you need specific details on how they should behave or additional resources to work on this.

Regarding the Flask-based interface: great start! I’d love to see the fire features integrated back. If you need any assistance or want me to take up a portion of the work (like debugging or testing), feel free to let me know.

Once again, I’m super grateful for your contributions and collaboration. Let’s push this project to the finish line! 🙌

Looking forward to hearing from you 😊

**Comment by i3hz** [comment]
Yeah all good man , I love working on this too its a lot of fun .
> Your contributions mean a lot, as I need to get this finalized soon to submit it.
I will try to do it before monday but well no promises as I also have my end semester exams going on and i have my own project to do 😞 
So yeah i'll try working on it .
> If you need any assistance or want me to take up a portion of the work (like debugging or testing), feel free to let me know.
I could use your help in testing any corner cases so I'll let you know when I'm done with implementing the flask interface

**Comment by i3hz** [comment]
Heyy I accidentally pushed my local repo here , I only added utils.py please revert it if its incorrect.
I'm sorry about this I thought I was pushing on my local fork . If it's incorrect let me know and revert back to the previous commit.
Really sorry for the inconvenience, that's my bad

**Comment by hackergandhi** [comment]
Hi @i3hz 
Don’t take too much stress. You can do whatever you feel is right, just let me know the changes you’ve made. I’ve done this much, and right now I’m extremely busy with another college project since its deadline is very near. Because of that, I’m unable to dedicate any time to the remaining project work. I also want to give you a reward of $30–$50. Would a Google Play redeem code work for you? Once all the work is completed, I’ll give you the reward.  
Once again, thank you so much!  😊

**Comment by hackergandhi** [comment]
And if you need anything else, you can DM me on my Instagram account: `___.loversland.___`

**Comment by i3hz** [comment]
https://github.com/i3hz/Lockbox-flask

hey man i did a bit of the UI , its kinda ugly atm but maybe i'll add some css later . It has adding password,saving it,and retrieval . Please test it and let me know if there are any issues . I'll probably do the css and styling later.

>I also want to give you a reward of $30–$50. Would a Google Play redeem code work for you? 
Damn nice thanks .But wel what about UPI or like idk amazon works too

**Comment by GumnaamSaaya** [comment]
Hi, 

> what about UPI or like idk amazon works too

amazon gift card?

> hey man i did a bit of the UI , its kinda ugly atm but maybe i'll add some css later . It has adding password,saving it,and retrieval . Please test it and let me know if there are any issues . I'll probably do the css and styling later.

I checked your repository: https://github.com/e3hz/lockbox-flask, and I found an error. Please have a look

```bash 
┌───────────────────────────────────────┐
│          Welcome to LockBoxXtreme      │
│         Your Secure Password Vault     │
└───────────────────────────────────────┘
🔒 Keep your passwords safe and secure! 🔒
Powered by LockBoxXtreme 💪


🔐 Set up your master password:
Enter a strong master password: nothing
🚨 Password must be 8+ chars with a mix of upper, lower, digits, and special chars.
🔐 Set up your master password:
Enter a strong master password: Gandhi@1
✅ Master password set successfully!
Enter your master password to proceed: Gandhi@1

==========================
        Main Menu
==========================
1. 🔐 Store a new password
2. 🔍 Retrieve a password
3. 🗑️  Delete a service
4. 💾 Create a backup
5. 🔄 Restore from a backup
6. 🔧 Generate a strong password
7. 🚪 Exit
==========================
Select an option (1-7): 1
Enter the service name: gandhi
Enter the password: Gandhi@123
Re-enter your master password: Gandhi@123
Traceback (most recent call last):
  File "/home/gandhi/Desktop/Targets/Lockbox-flask/main.py", line 157, in <module>
    main()
  File "/home/gandhi/Desktop/Targets/Lockbox-flask/main.py", line 129, in main
    store_password(service, password, master_password)
    ^^^^^^^^^^^^^^
NameError: name 'store_password' is not defined. Did you mean: 'master_password'?
```

**Comment by i3hz** [comment]
You are supposed to run app.py, main still has missing functions

**Comment by GumnaamSaaya** [comment]
The `app.py` is not working properly. When I run the `app.py` file and then go to `127.0.0.1:5000` in the browser, only the login page is showing up. It should first show the "set up master password" option and then move to the login page. But in this case, the login page is appearing directly, and it’s stuck there—it doesn’t proceed further

![image](https://github.com/user-attachments/assets/abe30305-bee5-49b8-96ec-8c2792294498)

logs:

![image](https://github.com/user-attachments/assets/88be5760-b06e-46bd-9155-24e6aff8d364)

**Comment by i3hz** [comment]
Ah I see the problem you are supposed to set master password first . I can fix it probably

**Comment by i3hz** [comment]
wait when you first run the app you go here where you can set the password
 ![image](https://github.com/user-attachments/assets/1e9000c7-e691-4c12-8ebd-e0a70d156301)

**Comment by i3hz** [comment]
I think the problem is where you clone the entire repo you're cloning my password.db file . So in your instance just delete the file and it should work

**Comment by i3hz** [comment]
hey I added some css with animations as well , lmk if thats working

**Comment by GumnaamSaaya** [comment]
Yeah, all good man! Your interface is very interesting, but I think you haven’t thoroughly checked out how my tool works. In my tool, the process starts with creating a master password and logging in, which is quite similar to your approach. I really liked that and appreciate it!

However, after logging in, there should be a page with the following options:

1. **Store a Password**  
2. **Retrieve Password**  
3. **Generate a Strong Password**  
4. **Update Master Password**  
5. **Delete Password by Service Name and Master Password**

These options could be presented on different pages or however you find suitable. Rn, your tool only has a dashboard page, which I liked, but I noticed a small issue. The stored service passwords are openly visible, which shouldn’t be the case. Instead, they should only be retrievable under the "Retrieve Password" option, where the user would enter the service name and master password to access the stored password.

You can check this implementation in my CLI version. Also, if you face any challenges with cryptographic functions during the development, feel free to reach out to me directly via Instagram—either call or message—because I sometimes miss checking emails

![image](https://github.com/user-attachments/assets/9e614796-41a0-4ab8-9386-f22dc51fd431)

**Comment by GumnaamSaaya** [comment]
Once you complete this development pls create a PR if you like this idea

**Comment by i3hz** [comment]
> The stored service passwords are openly visible, which shouldn’t be the case. Instead, they should only be retrievable under the "Retrieve Password" option, where the user would enter the service name and master password to access the stored password.<
---
Oh okay I can do that, though to ask the user for the password again would be tedious right, I mean you're already asking them for the password to log-in , so asking them for a password again just seems like extra work.

Oh and i dont use instagram, only discord D:

**Comment by GumnaamSaaya** [comment]
> so asking them for a password again just seems like extra work

No, it's not extra work; it's like double security, similar to 2FA (two-factor authentication) that you can think of

**Comment by GumnaamSaaya** [comment]
> Oh and i dont use instagram, only discord D: 

My discord username is `gumnaamsaaya`

**Comment by i3hz** [comment]
I added you on discord .
check the repo now i've done some changes .Also the retrieve password is still kinda funky can you help me with that. That and the 2FA thing are left

**Comment by GumnaamSaaya** [comment]
Hey man, please tell me what kind of help you need. Are you struggling to understand some function or something else? Let me know what needs to be done. Also, when I mentioned 2FA, I gave an example to show how entering a master password to retrieve a stored password works somewhat like 2FA

**Comment by i3hz** [comment]
I need help with the retrieve password function

**Comment by GumnaamSaaya** [comment]
@i3hz

here is a detailed, step-by-step plan for the implementation of master password check on the retrieve password functionality:

Steps for Master Password Verification in Password Retrieval

1) **update** `/retrieve_password` Route in `app.py`: Add a step to the `retrieve_password` route to verify the master password. Here's how:

```python
@app.route('/retrieve_password', methods=['GET', 'POST'])
def retrieve_password():
    if 'logged_in' not in session:
        return redirect(url_for('login'))
    
    passwords = []
    if request.method == 'POST':
        # Get inputs from the form
        service_name = request.form.get('service_name')
        entered_master_password = request.form.get('master_password')

        # Verify master password
        master_password_entry = MasterPassword.query.first()
        if not master_password_entry or not checkpw(entered_master_password.encode(), master_password_entry.password_hash.encode()):
            flash('Master password is incorrect!', 'error')
            return redirect(url_for('retrieve_password'))

        # Fetch and decrypt passwords
        entries = PasswordEntry.query.filter(
            PasswordEntry.service_name.ilike(f'%{service_name}%')
        ).all() if service_name else PasswordEntry.query.all()

        if not entries:
            flash(f'No passwords found{"" if not service_name else f" for {service_name}"}!', 'error')
        else:
            for entry in entries:
                decrypted_password = fernet.decrypt(entry.encrypted_password.encode()).decode()
                passwords.append({
                    'service': entry.service_name,
                    'password': decrypted_password
                })
    
    return render_template('retrieve_password.html', passwords=passwords)
```

2) **Update** `retrieve_password.html`: Add a field for entering the master password. The updated form should look like this:

```html
<form method="post" class="mb-4">
    <div class="form-group mb-3">
        <input type="text" name="service_name" class="form-control" 
               placeholder="Service Name (leave empty to show all passwords)">
    </div>
    <div class="form-group mb-3">
        <input type="password" name="master_password" class="form-control" 
               placeholder="Enter Master Password" required>
    </div>
    <button type="submit" class="btn btn-primary">Retrieve Passwords</button>
</form>
```

3) **Flash Error Messages:**  If the master password is incorrect or if no passwords are found, use the flash method to display an error message. These are already partially implemented in your app, but ensure they align with the above updates 

4) **Enhance Security:** Ensure the decrypted passwords are shown conditionally using the `togglePassword` JavaScript function already present in `retrieve_password.html`. This avoids exposing passwords directly in the response

To-Do List 

- Focus on implementing the UI updates, especially improving the CSS for better user experience
- Ensure `/retrieve_password` and other functionalities integrate properly with master password checks
- Proper error handling is in place
- Master password check works for each retrieval request

**Comment by GumnaamSaaya** [comment]
@i3hz 

If you want in CSS, I have a friend @Ajex911 who can do CSS. If you say so, he can help you with CSS because there is currently a significant lack of CSS in the project

**Comment by GumnaamSaaya** [comment]
Once you have completed all work please do ASAP merge files

**Comment by GumnaamSaaya** [comment]
@i3hz 

That's good, brother. I've been trying to hunt bugs on it and found two minor bugs, which I'll resolve myself later when I get some free time. I really appreciate all the hard work you've put in, and I want to let you know that I'll give you your reward by next week. I'll share the reward details on Discord. Also, can you create a PR and merge the files? But don't merge the `password.db` file you've created in the `instance` folder.

**Comment by i3hz** [comment]
Yeah sure sounds good to me , it was fun working on this  .

**Comment by GumnaamSaaya** [comment]
Bro, can you please create a PR and merge the files?

**Comment by i3hz** [comment]
I did  create one , should i merge it myself?

**Comment by i3hz** [comment]
well github is saying apparently that debug mode is bad , should i Enable or disable it?
debug mode basically reflects the changes in real time

**Comment by GumnaamSaaya** [comment]
> I did create one , should i merge it myself?

Yeah, you can merge the file yourself

**Comment by GumnaamSaaya** [comment]
> well github is saying apparently that debug mode is bad , should i Enable or disable it? debug mode basically reflects the changes in real time

Wait I'll see what happens here

**Comment by GumnaamSaaya** [comment]
> well github is saying apparently that debug mode is bad , should i Enable or disable it? debug mode basically reflects the changes in real time

Just merge the files brother, this is only informational

**Comment by GumnaamSaaya** [comment]
@i3hz 
`utils.py` What is the work of?

**Comment by i3hz** [comment]
Oh I forgot to remove that , remove it  , it's not needed

**Comment by GumnaamSaaya** [comment]
Thank you, @i3hz , for contributing to my project. It's because of you that this project turned out so well. I think we should mark this issue as complete now. If you feel something else needs to be addressed, you can always reopen it
